---
- hosts: azure
  become: yes
  vars:
   - mysql_new_root_pass: IamSoSecret
   - wordpress_db: wordpress
   - wordpress_user: wpuser
   - wordpress_user_passwd: wpuserpwd
   - apache_ssl_site: wordpress-ssl
   - apache_server_admin: zkzko@hotmail.com
   - DocumentRoot: /var/www/html
   - LetsencryptDir: /var/www/letsencrypt/.well-known/acme-challenge
   - DomName: u2004.delatia.ch
  roles:
   - common
   - php
   - apache2
   - mariadb
   - wordpress
   - getssl
