---
- import_tasks: apache_php_lib72.yml
  when: ansible_distribution_version == "19.04"

- import_tasks: apache_php_lib73.yml
  when: ansible_distribution_version == "19.10"

- import_tasks: apache_php_lib74.yml
  when: ansible_distribution_version == "20.04"

- name: copy locally created files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:  
     - {src: dir.conf, dest: /etc/apache2/mods-available/dir.conf}
     - {src: ssl.conf, dest: /etc/apache2/mods-available/ssl.conf}
     - {src: .htaccess, dest: "{{ DocumentRoot }}/.htaccess"}
  notify:
  - restart apache2

- name: create apache sites in sites-available
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: yes
  with_items:
     - {src: 000-default.conf, dest: /etc/apache2/sites-available/000-default.conf}
     - {src: "{{ apache_ssl_site }}.conf", dest: "/etc/apache2/sites-available/{{ apache_ssl_site }}.conf"}

- name: Enable common apache modules
  apache2_module: name={{ item }}
  with_items:
    - ssl
    - rewrite
    - headers

- name: a2ensite {{ apache_ssl_site }}
  command: a2ensite {{ apache_ssl_site }}
  args:
    creates: /etc/apache2/sites-enabled/{{ apache_ssl_site }}.conf
  notify:
  - restart apache2
