---
- name: copy WordPress into tmp
  copy: src=wordpress-5.2.3-de_CH.tar.gz dest=/tmp/wordpress.tar.gz

- name: unzip WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/tmp copy=no creates=/tmp/wordpress/wp-setings.php

- name: copy Wordpress to /var/www/html
  copy: src=/tmp/wordpress/ dest=/var/www/html owner=www-data group=www-data mode=0755 remote_src=yes

- name: create WordPress MySQL database
  mysql_db: name={{ wordpress_db }} state=present

- name: create WordPress MySQL user
  mysql_user: name={{ wordpress_user }} host=localhost password={{ wordpress_user_passwd }} priv=wordpress.*:ALL state=present

- name: create wp-config.php
  template: src=wp-config.php dest=/var/www/html/wp-config.php

