---
- name: install PHP
  apt:
   name: "{{ list_of_packages }}"
   state: latest
   update_cache: yes
  vars:
   list_of_packages:
     - php7.2
     - php7.2-mysql
     - libapache2-mod-php7.2
     - php7.2-cli
     - php7.2-cgi
     - php7.2-gd

