---
- name: install PHP
  apt:
   name: "{{ list_of_packages }}"
   state: latest
   update_cache: yes
  vars:
   list_of_packages:
     - php7.3
     - php7.3-mysql
     - libapache2-mod-php7.3
     - php7.3-cli
     - php7.3-cgi
     - php7.3-gd

- name: set PHP post_max_size
  become: yes
  ini_file:
    path: /etc/php/7.3/apache2/php.ini
    section: PHP
    option: post_max_size
    value: 8M

- name: set PHP upload_max_filesize
  become: yes
  ini_file:
    path: /etc/php/7.3/apache2/php.ini
    section: PHP
    option: upload_max_filesize
    value: 3M

